# Makefile für das C-Projekt

prog: TestComplex.o complex.o
			gcc -o testMake TestComplex.o complex.o

TestComplex.o:TestComplex.c
				gcc -c TestComplex.c
complex.o:complex.c
			gcc -c complex.c
clean: